In [24]:
import pandas as pd

#read in the raw star wars data set by the url

star_wars = pd.read_csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/star-wars-survey/StarWars.csv')

star_wars_head = star_wars.head(2)
print star_wars_head
print'\n'
print('The head funcion allows us to see the first few rows of the data set (the default \nnumber of rows is 5 but you can specify otherwise)')
print'\n'
print'\n'

star_wars_tail = star_wars.tail(2)
print star_wars_tail
print'\n'
print('The tail function allows us to see the last few rows of the data set, just \nlike the head function does for the first rows')
print'\n'
print'\n'

star_wars_summary = star_wars.describe()
print star_wars_summary
print'\n'
print('The describe function shows us some of the summary statistics (count, mean, std, etc...) \n for the dataset')

   RespondentID Have you seen any of the 6 films in the Star Wars franchise?  \
0           NaN                                           Response
1  3.292880e+09                                                Yes

  Do you consider yourself to be a fan of the Star Wars film franchise?  \
0                                           Response
1                                                Yes

  Which of the following Star Wars films have you seen? Please select all that apply.  \
0           Star Wars: Episode I  The Phantom Menace
1           Star Wars: Episode I  The Phantom Menace

                                    Unnamed: 4  \
0  Star Wars: Episode II  Attack of the Clones
1  Star Wars: Episode II  Attack of the Clones

                                    Unnamed: 5  \
0  Star Wars: Episode III  Revenge of the Sith
1  Star Wars: Episode III  Revenge of the Sith

                          Unnamed: 6  \
0  Star Wars: Episode IV  A New Hope
1  Star Wars: Episode IV  A New Hope

                                     Unnamed: 7  \
0  Star Wars: Episode V The Empire Strikes Back
1  Star Wars: Episode V The Empire Strikes Back

                                 Unnamed: 8  \
0  Star Wars: Episode VI Return of the Jedi
1  Star Wars: Episode VI Return of the Jedi

  Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.  \
0           Star Wars: Episode I  The Phantom Menace
1                                                  3

            ...                Unnamed: 28       Which character shot first?  \
0           ...                       Yoda                          Response
1           ...             Very favorably  I don't understand this question

  Are you familiar with the Expanded Universe?  \
0                                     Response
1                                          Yes

  Do you consider yourself to be a fan of the Expanded Universe?��  \
0                                           Response
1                                                 No

  Do you consider yourself to be a fan of the Star Trek franchise?    Gender  \
0                                           Response                Response
1                                                 No                    Male

        Age Household Income           Education Location (Census Region)
0  Response         Response            Response                 Response
1     18-29              NaN  High school degree           South Atlantic

[2 rows x 38 columns]


The head funcion allows us to see the first few rows of the data set (the default
number of rows is 5 but you can specify otherwise)




      RespondentID  \
1185  3.288373e+09
1186  3.288373e+09

     Have you seen any of the 6 films in the Star Wars franchise?  \
1185                                                Yes
1186                                                Yes

     Do you consider yourself to be a fan of the Star Wars film franchise?  \
1185                                                Yes
1186                                                 No

     Which of the following Star Wars films have you seen? Please select all that apply.  \
1185           Star Wars: Episode I  The Phantom Menace
1186           Star Wars: Episode I  The Phantom Menace

                                       Unnamed: 4  \
1185  Star Wars: Episode II  Attack of the Clones
1186  Star Wars: Episode II  Attack of the Clones

                                       Unnamed: 5  \
1185  Star Wars: Episode III  Revenge of the Sith
1186                                          NaN

                             Unnamed: 6  \
1185  Star Wars: Episode IV  A New Hope
1186                                NaN

                                        Unnamed: 7  \
1185  Star Wars: Episode V The Empire Strikes Back
1186  Star Wars: Episode V The Empire Strikes Back

                                    Unnamed: 8  \
1185  Star Wars: Episode VI Return of the Jedi
1186  Star Wars: Episode VI Return of the Jedi

     Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.  \
1185                                                  4
1186                                                  6

               ...                  Unnamed: 28  \
1185           ...               Very favorably
1186           ...             Very unfavorably

           Which character shot first?  \
1185                               Han
1186  I don't understand this question

     Are you familiar with the Expanded Universe?  \
1185                                           No
1186                                           No

     Do you consider yourself to be a fan of the Expanded Universe?��  \
1185                                                NaN
1186                                                NaN

     Do you consider yourself to be a fan of the Star Trek franchise?  Gender  \
1185                                                Yes                Female
1186                                                 No                Female

        Age     Household Income                         Education  \
1185  45-60  $100,000 - $149,999  Some college or Associate degree
1186   > 60    $50,000 - $99,999                   Graduate degree

     Location (Census Region)
1185       East North Central
1186                  Pacific

[2 rows x 38 columns]


The tail function allows us to see the last few rows of the data set, just
like the head function does for the first rows




       RespondentID
count  1.186000e+03
mean   3.290128e+09
std    1.055639e+06
min    3.288373e+09
25%    3.289451e+09
50%    3.290147e+09
75%    3.290814e+09
max    3.292880e+09


The describe function shows us some of the summary statistics (count, mean, std, etc...)
 for the dataset

In [25]:
#Select a certain column
print(star_wars[1:2])

   RespondentID Have you seen any of the 6 films in the Star Wars franchise?  \
1  3.292880e+09                                                Yes

  Do you consider yourself to be a fan of the Star Wars film franchise?  \
1                                                Yes

  Which of the following Star Wars films have you seen? Please select all that apply.  \
1           Star Wars: Episode I  The Phantom Menace

                                    Unnamed: 4  \
1  Star Wars: Episode II  Attack of the Clones

                                    Unnamed: 5  \
1  Star Wars: Episode III  Revenge of the Sith

                          Unnamed: 6  \
1  Star Wars: Episode IV  A New Hope

                                     Unnamed: 7  \
1  Star Wars: Episode V The Empire Strikes Back

                                 Unnamed: 8  \
1  Star Wars: Episode VI Return of the Jedi

  Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.  \
1                                                  3

            ...                Unnamed: 28       Which character shot first?  \
1           ...             Very favorably  I don't understand this question

  Are you familiar with the Expanded Universe?  \
1                                          Yes

  Do you consider yourself to be a fan of the Expanded Universe?��  \
1                                                 No

  Do you consider yourself to be a fan of the Star Trek franchise? Gender  \
1                                                 No                 Male

     Age Household Income           Education Location (Census Region)
1  18-29              NaN  High school degree           South Atlantic

[1 rows x 38 columns]

In [26]:
#slice for a set of rows
print(star_wars.iloc[1:3 , :])

   RespondentID Have you seen any of the 6 films in the Star Wars franchise?  \
1  3.292880e+09                                                Yes
2  3.292880e+09                                                 No

  Do you consider yourself to be a fan of the Star Wars film franchise?  \
1                                                Yes
2                                                NaN

  Which of the following Star Wars films have you seen? Please select all that apply.  \
1           Star Wars: Episode I  The Phantom Menace
2                                                NaN

                                    Unnamed: 4  \
1  Star Wars: Episode II  Attack of the Clones
2                                          NaN

                                    Unnamed: 5  \
1  Star Wars: Episode III  Revenge of the Sith
2                                          NaN

                          Unnamed: 6  \
1  Star Wars: Episode IV  A New Hope
2                                NaN

                                     Unnamed: 7  \
1  Star Wars: Episode V The Empire Strikes Back
2                                           NaN

                                 Unnamed: 8  \
1  Star Wars: Episode VI Return of the Jedi
2                                       NaN

  Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.  \
1                                                  3
2                                                NaN

            ...                Unnamed: 28       Which character shot first?  \
1           ...             Very favorably  I don't understand this question
2           ...                        NaN                               NaN

  Are you familiar with the Expanded Universe?  \
1                                          Yes
2                                          NaN

  Do you consider yourself to be a fan of the Expanded Universe?��  \
1                                                 No
2                                                NaN

  Do you consider yourself to be a fan of the Star Trek franchise? Gender  \
1                                                 No                 Male
2                                                Yes                 Male

     Age Household Income           Education Location (Census Region)
1  18-29              NaN  High school degree           South Atlantic
2  18-29     $0 - $24,999     Bachelor degree       West South Central

[2 rows x 38 columns]

In [27]:
#Select a data point based on specific position
#this should be the value in the second row, third column
print(star_wars.iloc[1, 2])

Yes

In [33]:
pd.to_numeric(star_wars, )

TypeError: arg must be a list, tuple, 1-d array, or Series

In [46]:
#Convert 
change_column = star_wars.iloc[1:, 0]
change_column = change_column.astype(int)

print change_column
print change_column.dtypes

1       3292879998
2       3292879538
3       3292765271
4       3292763116
5       3292731220
6       3292719380
7       3292684787
8       3292663732
9       3292654043
10      3292640424
11      3292637870
12      3292635062
13      3292609214
14      3292596911
15      3292587240
16      3292583038
17      3292580516
18      3292572872
19      3292565282
20      3292562297
21      3292522349
22      3292521066
23      3292511801
24      3292483200
25      3292465491
26      3292447974
27      3292420123
28      3292384040
29      3292380493
30      3292376985
           ...
1157    3288425859
1158    3288423088
1159    3288423045
1160    3288421819
1161    3288420798
1162    3288417782
1163    3288417641
1164    3288416959
1165    3288415166
1166    3288414025
1167    3288413441
1168    3288410348
1169    3288410073
1170    3288408698
1171    3288402717
1172    3288402643
1173    3288402592
1174    3288402511
1175    3288401681
1176    3288401136
1177    3288398062
1178    3288396374
1179    3288395255
1180    3288391812
1181    3288389603
1182    3288388730
1183    3288378779
1184    3288375286
1185    3288373068
1186    3288372923
Name: RespondentID, dtype: int64
int64

In [55]:
#Create a dummy variable for yes and no answers
dummy_column = star_wars.iloc[1:, 1]
pd.get_dummies(dummy_column)

       No  Yes
1     0.0  1.0
2     1.0  0.0
3     0.0  1.0
4     0.0  1.0
5     0.0  1.0
6     0.0  1.0
7     0.0  1.0
8     0.0  1.0
9     0.0  1.0
10    0.0  1.0
11    0.0  1.0
12    1.0  0.0
13    0.0  1.0
14    0.0  1.0
15    0.0  1.0
16    0.0  1.0
17    0.0  1.0
18    0.0  1.0
19    0.0  1.0
20    0.0  1.0
21    0.0  1.0
22    0.0  1.0
23    0.0  1.0
24    0.0  1.0
25    0.0  1.0
26    1.0  0.0
27    0.0  1.0
28    0.0  1.0
29    0.0  1.0
30    0.0  1.0
...   ...  ...
1157  0.0  1.0
1158  1.0  0.0
1159  0.0  1.0
1160  1.0  0.0
1161  0.0  1.0
1162  0.0  1.0
1163  0.0  1.0
1164  0.0  1.0
1165  0.0  1.0
1166  0.0  1.0
1167  0.0  1.0
1168  0.0  1.0
1169  1.0  0.0
1170  0.0  1.0
1171  1.0  0.0
1172  0.0  1.0
1173  0.0  1.0
1174  0.0  1.0
1175  0.0  1.0
1176  0.0  1.0
1177  0.0  1.0
1178  0.0  1.0
1179  1.0  0.0
1180  0.0  1.0
1181  0.0  1.0
1182  0.0  1.0
1183  0.0  1.0
1184  1.0  0.0
1185  0.0  1.0
1186  0.0  1.0

[1186 rows x 2 columns]